<a href="https://colab.research.google.com/github/shemi024/Packages/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world")

hello world


***# numy array***


In [ ]:
import numpy as np
a=np.array([1, 2, 3, 4, 4])
print(a)

[1 2 3 4 4]


In [ ]:
type(a)

numpy.ndarray

In [ ]:
a[:2]


array([1, 2])

In [ ]:
a[3]

4

In [ ]:
a[0]=5.
print(a)

[5 2 3 4 4]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)


[[1 2 3]
 [4 5 6]]


In [ ]:
a[0,0]

1

In [ ]:
a[0,1]

2

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
a[1,:]

array([4, 5, 6])

In [ ]:
a[:,2]

array([3, 6])

In [ ]:
a[-1:,-2:]

array([[5, 6]])

In [ ]:
a.shape

(2, 3)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
len(a)

2

In [ ]:
2 in a

True

In [ ]:
6 in a

True

In [ ]:
11 in a

False

In [ ]:
a=np.array(range(10))
a=a.reshape((5,2))
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
a.shape

(5, 2)

*COAPY*


In [ ]:
a=np.array([1,2,3])
b=a
c=a.copy()
a[0]=0
a


array([0, 2, 3])

In [ ]:
b

array([0, 2, 3])

**TO LIST
**

In [ ]:
a=np.array([1,2,3],float)
a.tolist()

[1.0, 2.0, 3.0]

In [ ]:
list(a)

[1.0, 2.0, 3.0]